"""tables

Revision ID: 0b1a8866a985
Revises: 
Create Date: 2025-06-15 07:46:31.152745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1a8866a985'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_balances',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('authorized_balance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.String(length=15), nullable=False),
    sa.Column('invoice_id_alt', sa.String(length=15), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hpan', sa.String(length=16), nullable=False),
    sa.Column('exp_date', sa.String(length=4), nullable=False),
    sa.Column('cvc', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('post_link', sa.String(length=2048), nullable=False),
    sa.Column('failure_post_link', sa.String(length=2048), nullable=True),
    sa.Column('card_save', sa.Boolean(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('terminal_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('int_reference', sa.String(length=255), nullable=True),
    sa.Column('approval_code', sa.String(length=6), nullable=True),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id_alt')
    )
    op.create_index(op.f('ix_transactions_invoice_id'), 'transactions', ['invoice_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_invoice_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('account_balances')
    # ### end Alembic commands ###
