"""transaction: добавил поле для оригинальной транзакции, чтобы реализовать удобный возврат средств

Revision ID: de3a9a574be5
Revises: f2e089f1528f
Create Date: 2025-06-02 12:33:13.805552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3a9a574be5'
down_revision: Union[str, None] = 'f2e089f1528f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('original_transaction_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'original_transaction_id')
    # ### end Alembic commands ###
