"""добавлено поле held_balance в accounts

Revision ID: 4a6f124dcc1d
Revises: 9e4edf519d36
Create Date: 2025-05-30 11:04:18.206746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6f124dcc1d'
down_revision: Union[str, None] = '9e4edf519d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('held_balance', sa.DECIMAL(precision=15, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'held_balance')
    # ### end Alembic commands ###
