"""Создание таблицы cards

Revision ID: 4e231a3ad1e5
Revises: 6b7fcde2de73
Create Date: 2025-05-28 11:00:06.268723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e231a3ad1e5'
down_revision: Union[str, None] = '6b7fcde2de73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('expiry_date', sa.DATE(), nullable=False),
    sa.Column('cvc', sa.VARCHAR(length=4), nullable=False),
    sa.Column('cardholder_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('issue_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('card_status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
