"""update clients table

Revision ID: 4e855c366bf5
Revises: 5b81589d737f
Create Date: 2025-05-27 19:39:23.974083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e855c366bf5'
down_revision: Union[str, None] = '5b81589d737f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    '''Upgrade schema.
    
    Ниже - костыль. Возможно, что есть решение получше.

    Суть заключается в том, что изначально была создан столбец date_of_birth
    неправильного типа данных в предыдущей миграции. Эта миграция должна
    исправить это, но alembic автоматически не смог решить эту проблему,
    поэтому пришлось думать как решить эту проблему.

    alembic после ошибки выплюнул запрос, который находится в op.execute(), 
    без части USING, который по-сути является операцией выше, которая
    закомментирована. Оператором USING уже дополнил сам postgresql своей
    подсказкой, после выполнения этой команды.
    
    Теперь, миграция работает.
    
    Ниже - остатки от alembic.

    commands auto generated by Alembic - please adjust!

    op.alter_column('clients', 'date_of_birth',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=False)
    '''


    op.execute('ALTER TABLE clients ALTER COLUMN date_of_birth TYPE DATE USING date_of_birth::date;')
    op.alter_column('clients', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    '''Downgrade schema.
    
    Работает исправно, исправлений не понадобилось.
    '''
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'address',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('clients', 'date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
