name: praktika1

# DB_PASSWORD, DB_DATA_LOCATION - стягиваются из .env файла
services:
  postgres:
    image: "docker.io/postgres:latest"
    ports: 
      - 5432:${DB_PORT}
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes: 
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
        
  redis:
    image: "docker.io/redis:latest"
    restart: always
